### ISSUE TITLE
Create Honeybee Object primitive in GH for picking up HB geometries created from Rhino

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-grasshopper-energy#16]
We need to create a HBObject grasshopper primitive to contain HoneybeeRhino object.

**Comment by chriswmackey** [comment]
This issue belongs on this repo:
https://github.com/ladybug-tools/honeybee-grasshopper-core/issues

Can you repoen it over there @MingboPeng ?
