### ISSUE TITLE
Bake/Internalize Honeybee GH object

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-grasshopper-energy#17]
We should be providing these:
-Bake Honeybee GH geometry object to Honeybee Rhino geometry object.
-Internalize Honeybee GH object in HBObject primitive.

**Comment by chriswmackey** [comment]
Doesn't this issue belong in the Honeybee-Rhino repo?  We won't be able to do any of this stuff without the Honeybee-Rhino objects like Room entity, etc.

I think the only one that belongs here is this one: https://github.com/ladybug-tools/honeybee-grasshopper-energy/issues/19

**Comment by chriswmackey** [comment]
Thinking about it more, it definitely doesn't belong on this repo. If it belongs on any of the Grasshopper repos, it belongs over here:
https://github.com/ladybug-tools/honeybee-grasshopper-core

Can you reopen the issue over there (assuming that there is some non-rhino-plugin development that needs to happen for this).
