### ISSUE TITLE
Share the same global program types library between HBRhino and HBGH

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/honeybee-grasshopper-energy#18]
Users should not be worried about where to create or edit program type library. 
Two platforms should be using the same global library (program type, construction, schedule), and any updates will need to be synced.

**Comment by chriswmackey** [comment]
This issue does not belong in this repo. It belongs on the repo that actually houses the library of global program types and templates:https://github.com/ladybug-tools/honeybee-energy-standards/issues/22
