### ISSUE TITLE
add_str_ error in HB Run OSW

### ISSUE THREAD

**Issue by marctavenier** [ladybug-tools/honeybee-grasshopper-energy#335]
Hi,

As indicated [here](https://discourse.ladybug.tools/t/hb-run-osw-component/14792), the HB Run OSW etc components crash when using the add_str_ functionality.
Change line https://github.com/ladybug-tools/honeybee-grasshopper-energy/blob/16c0c21148861f8d6f5c091c9d7da949e457111a/honeybee_grasshopper_energy/src/HB%20Run%20OSW.py#L83 to 
`with open(idf_i, "a") as idf_file:`

Perhaps the same occurs in HB Run OSM and HB Run IDF, but I haven't tested this.

Kind regards,
Marc

**Comment by chriswmackey** [comment]
Thanks for finding and reporting the issue, @marctavenier . Sorry that it took so long for me to check this. The fix is here:

https://github.com/ladybug-tools/honeybee-grasshopper-energy/pull/359
