### ISSUE TITLE
Hot water bug in HB Thermal Load Balance

### ISSUE THREAD

**Issue by marctavenier** [ladybug-tools/honeybee-grasshopper-energy#353]
Hi,

I believe the following two lines of code https://github.com/ladybug-tools/honeybee-grasshopper-energy/blob/ef5948a23e36901e74e07c330fbe12ff2e0c585c/honeybee_grasshopper_energy/src/HB%20Thermal%20Load%20Balance.py#L136-L137 should read 
```
        hot_water_ = [hw * 0.25 for hw in hot_water_]
        for hw in hot_water_:
```
That way here: https://github.com/ladybug-tools/honeybee-grasshopper-energy/blob/ef5948a23e36901e74e07c330fbe12ff2e0c585c/honeybee_grasshopper_energy/src/HB%20Thermal%20Load%20Balance.py#L144-L147 the processed hot water is referenced, as opposed to the original hot water.

Kind regards,
Marc

**Comment by mostaphaRoudsari** [comment]
Thank you, @marctavenier - I assigned this to Chris to have a look.

**Comment by chriswmackey** [comment]
Thanks again, @marctavenier !
