### ISSUE TITLE
Solution exception: global name 'OrderedDict' is not defined

### ISSUE THREAD

**Issue by maximilian-klein** [ladybug-tools/honeybee-grasshopper-energy#367]
I'am new to HB-Energy and I have the following Problem with the HB End Use Intensity. I am following this [Energy Fundamentals: Running a Simulation](https://www.youtube.com/watch?v=tEaznvN5590&list=PLtSMbRCHXHVGeqcgxxE7U_GY3eUnc2Lpp&index=10 ) Tutorial. When I try to use the EUI I got the Issue: Solution exception: global name 'OrderedDict' is not defined.

Setup:
Mac OS 16.6.2
Rhino 7
Ladybug Tools 1.6.0
Python 3.79
Radiance 5.4a
Openstudio 3.5.0

**Comment by mostaphaRoudsari** [comment]
Hi @maximilian-klein - can you be more specific about the component and provide the full error message? You can get the full error message by connecting a panel to the `out` or `report` output. If there is no such and output, double-click on the component to open the editor and try to run the component again. You should see the full error message.

**Comment by maximilian-klein** [comment]
When I open the editor and run the Python File I get: 

  Error: Runtime error (UnboundNameException): global name 'OrderedDict' is not defined

Traceback:
  line 87, in get_results_mac, "<string>"
  line 98, in script

I didn't know that I can open the Python Editor thanks for that hint. I fixed the Problem with:

import collections

try:
    from collections import OrderedDict
except ImportError:
    OrderedDict = dict

**Comment by chriswmackey** [comment]
Thanks for reporting, @maximilian-klein and I'm sorry for not responding sooner.

The `collections` module and the `OrderedDict` object are native Python so they should be available on the Python that we ship with the Mac plugin.

I had thought that the latest available version of mac OS is 13. How were you able to get version 16 or am I just misunderstanding here?

Also, can you import OrderedDict natively in a GHPython component like so?
![image](https://user-images.githubusercontent.com/5567574/226438442-567407cf-261f-4f59-a505-a11370117f01.png)

https://drive.google.com/file/d/1WdoS_QSNfbFkQofqCKBHQpUl5l0VL8Ol/view?usp=sharing
