### ISSUE TITLE
Figure out how to bypass the lack of a working sqlite3 module on GHPython for Mac

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-grasshopper-energy#67]
It seems that the sqlite3 module in GHPython for Mac does not work. Whenever it gets to the point where I execute an SQLite query, I get the following error:

```
Runtime error (EntryPointNotFoundException): LockFileEx assembly:<unknown assembly> type:<unknown type> member:(null)
```

Creating the connection, pointing the cursor, and everything else succeeds. It's just the execution of the query.

From what I can tell from my quick research, it's specifically because of using IronPython on Mac and there doesn't seem to be any way to get this to work.  I verified that the sqlite3 queries work perfectly fine with a standalone installation of Python 3.7 on mac. So it seems that the only way around this might be to add CLI commands to run the SQL module and return dictionaries of the data collections.

@mostaphaRoudsari and @mingbopeng , do you have any thoughts about how we could address this?

**Comment by mostaphaRoudsari** [comment]
I think this is something that we should report to McNeel and see if they can come up with a fix.

Meanwhile your solution sounds good to me. I suggest to use C/Pickle instead of using JSON in this case for de/serializing data. It will most likely be faster in this case specially for large amounts of data.

**Comment by chriswmackey** [comment]
Thanks @mostaphaRoudsari . I had the same thought. Is the best place to report this to McNeel on their discourse forum? Or should we try to reach out to Guilio directly?

For the workaround, I was thinking of just pushing the data collection dictionary to stdout in order to avoid writing the file. Can this same thing be done easily with the C/Pickle serialization?

**Comment by mostaphaRoudsari** [comment]
I think we should post it on the forum. If we didn't hear back we can send a note to Steve who I assume is the person in charge.

I'm not sure. If the JSONiftying the studout gives you the performance that you are looking for then we can disregard my suggestion.

**Comment by chriswmackey** [comment]
Posted to the McNeel forum: https://discourse.mcneel.com/t/ghpython-sqlite3-module-is-unusable-on-mac/103324

I will go the pickle route if I find that I have to write the results to a file or the performance of the JSON workflow is particularly bad.

**Comment by chriswmackey** [comment]
Forgot to close this. This has now been addressed.
